- name: KIBANA | Deploy Kibana systemd units
  template:
    src: kibana.service.j2
    dest: /etc/systemd/system/kibana.service

- name: KIBANA | Flush Handlers
  meta: flush_handlers

- name: KIBANA | Enable Kibana
  service:
    name: kibana
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: KIBANA | Wait for service become running
  wait_for:
    port: 5601
    host: "127.0.0.1"