- name: PROMETHEUS | Deploy Prometheus systemd units
  template:
    src: Prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: PROMETHEUS | Create directory
  file:
    path: "{{ item }}"
    state: "directory"
    group: 65534
    owner: 65534
  with_items:
    - /var/lib/volume/prometheus
    - /etc/prometheus/

- name: PROMETHEUS | Deploy Prometheus conf
  template:
    src: "{{ item }}.j2"
    dest: /etc/prometheus/{{ item }}
  with_items:
    - prometheus.yml
  notify: Restart prometheus

- name: PROMETHEUS | Flush Handlers
  meta: flush_handlers

- name: PROMETHEUS | Enable Prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: PROMETHEUS | Wait for service become running
  wait_for:
    port: 9090
    host: "127.0.0.1"
