{
 "title": "Crawler Tags",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency: Summarized by hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(postssummarized_latency_seconds_sum/postssummarized_latency_seconds_count)"
    }
   ]
  },
  {
   "title": "Total errors: Summarized by hour",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "postssummarized_errors_counter" }
   ]
  },
  {
   "title": "Latency: Top followers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(topfollowers_latency_seconds_sum/topfollowers_latency_seconds_count)"
    }
   ]
  },
  {
   "title": "Total errors: Top Followers",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "topfollowers_errors_counter" }
   ]
  },
  {
   "title": "Latency: Total posts by language",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(totalposts_latency_seconds_sum/totalposts_latency_seconds_count)"
    }
   ]
  },
  {
   "title": "Total errors: Total posts by language",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "totalPosts_errors_counter" }
   ]
  }
 ]
}