- name: LOGSTASH | Deploy Logstash systemd units
  template:
    src: logstash.service.j2
    dest: /etc/systemd/system/logstash.service

- name: LOGSTASH | Create directory
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /etc/logstash

- name: LOGSTASH | Create directory
  copy:
    src: "../../../../logstash"
    dest: "/etc/logstash"
  notify: Restart logstash

- name: LOGSTASH | Flush Handlers
  meta: flush_handlers

- name: LOGSTASH | Enable Logstash
  service:
    name: logstash
    state: restarted
    enabled: yes
    daemon_reload: yes
