- name: ETCD3 | Deploy ETCD3 systemd units
  template:
    src: etcd3.service.j2
    dest: /etc/systemd/system/etcd3.service

- name: ETCD3 | Create directory
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /etc/volume/etcd

- name: ETCD3 | Flush Handlers
  meta: flush_handlers

- name: ETCD3 | Enable ETCD3
  service:
    name: etcd3
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: ETCD3 | Wait for service become running
  wait_for:
    port: 2379
    host: "127.0.0.1"