- name: ELASTICSEARCH | Deploy ElasticSearch systemd units
  template:
    src: elasticsearch.service.j2
    dest: /etc/systemd/system/elasticsearch.service

- name: ELASTICSEARCH | Flush Handlers
  meta: flush_handlers

- name: ELASTICSEARCH | Enable ElasticSearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: ELASTICSEARCH | Wait for service become running
  wait_for:
    port: 9200
    host: "127.0.0.1"