- name: NGINX | Deploy Nginx systemd units
  template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service

- name: NGINX | Create directory
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - /etc/nginx
    - /etc/nginx/conf.d

- name: NGINX | Deploy Nginx conf
  template:
    src: "{{ item }}.j2"
    dest: /etc/nginx/{{ item }}
  with_items:
    - nginx.conf
    - mime.types
  notify: Restart nginx

- name: NGINX | Flush Handlers
  meta: flush_handlers

- name: NGINX | Enable Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: NGINX | Wait for service become running
  wait_for:
    port: 80
    host: "127.0.0.1"