- name: GRAFANA | Deploy Grafana systemd units
  template:
    src: grafana.service.j2
    dest: /etc/systemd/system/grafana.service

- name: GRAFANA | Flush Handlers
  meta: flush_handlers

- name: GRAFANA | Enable Grafana
  service:
    name: grafana
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: GRAFANA | Wait for service become running
  wait_for:
    port: 3000
    host: "127.0.0.1"
